version: "3"

services:
    drupal:
        image: gardensgreen/custom-drupal
        build: .
        ports:
            - 8080:80
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_PASSWORD=password
        volumes:
            # now every time we boot up compose we will have the
            # same password and data available to us
            - drupal-data:/var/lib/postgresql/data
volumes:
    drupal-data:
